config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users
  get 'users/:id' => 'users#show', as: 'users_show'
  get 'users'=> 'users#index'

  resources :microposts,          only: [:index, :edit, :create, :destroy]
  
  get 'addfriend/:id' => 'friendship#friend_request', as: 'add_friend'

  get 'requests' => 'friendship#pending_request', as: 'pending_request'

  get 'friends' => 'friendship#friends', as: 'friends'
 
  get 'accecpt_request/:id' => 'friendship#friend_request_accept' , as: 'accecpt_request'

  delete 'reject_request/:id' => 'friendship#friend_request_reject' , as: 'reject_request'

  get 'like/:id' => 'users#like' , as: 'like_unlike' 

  get 'posts/:id' =>'microposts#showpost', as: 'posts_show'

  post 'add_comment' =>  'microposts#add_comment', as: 'add_comment'

  

 

    

end

app/models/user.rb
class User < ActiveRecord::Base
  # has_one :role
  belongs_to :role
  has_many :microposts, dependent: :destroy
  has_many :from_friendships, :foreign_key => :from_id, class_name: 'Friendship'
  has_many :to_friendships, :foreign_key => :to_id, class_name: 'Friendship'
  has_many :users, through: :friendships
  has_many :voter_relationships
  has_many :commenters
  validates :username, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  def is_friend?(friend_id)
    friend = Friendship.where(to_id: friend_id, from_id: self.id, accepted: true).first
    # friend1 = Friendship.where(to_id: self.id, from_id: friend_id, accepted: true).first
    if friend.nil?
      false
    else
      true
    end
  end

  def is_other_user_friend?(friend_id)
    # friend = Friendship.where(to_id: friend_id, from_id: self.id, accepted: true).first
    friend = Friendship.where(to_id: self.id, from_id: friend_id, accepted: true).first
    if friend.nil?  #|| friend1.nil?
      false
    else
      true
    end
  end

  def is_pending_request?(friend_id)
    friend = Friendship.where(to_id: friend_id, from_id: self.id, accepted: false).first
    if friend.nil?
      false
    else
      true
    end
  end
  
  # def get_friends
  #   friends = []
  #   self.from_friendships.each do |from_friend|
  #     friends << from_friend.from_user
  #   end

  #   self.to_friendships.each do |to_friend|
  #     friends << to_friend.to_user
  #   end

  #   # from_friends = Friendship.where(from_id: self.id)
  #   # from_friends.each do |from_friend|
  #   #   friends << from_friend.from_user
  #   # end
  #   friends
  # end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
	def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])

    @user_id =  User.find(params[:user_id]) 
  end

  def index
  	 @users = User.paginate(page: params[:page])
  end
  def new
    @user = User.new
  end

  def like
    logger.debug '11111111111111111111111'
    logger.debug params
    # vr = VoterRelation.new(post_id: params[:post_id], user_id: current_user.id)
    # vr = current_user.voter_relationships.new(post_id: params[:post_id])
    post = Micropost.where(id: params[:post_id]).first
    if post.present?
      vr = post.voter_relationships.new(user_id: current_user.id)
      if vr.save
        flash[:notice] = 'Liked'
        redirect_to microposts_path
      else
        flash[:error] = 'There is some issue liking the post.'
        redirect_to microposts_path
      end
    else
      flash[:error] = 'No posts available for like'
      redirect_to microposts_path
    end
  end


		
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
	def show
    # @user = User.paginate(page: params[:page])
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])

    # @user_id =  User.find(params[:user_id]) 
  end

  # def showpost
  #   @user = User.find(params[:id])
  #   @micropost = Micropost.Where(id: params[:post_id], user_id: params[:id])
  # end


  def index
  	@users = User.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end  

  def like

    post = Micropost.where(id: params[:id]).first
    if post.present?
      is_liked = VoterRelationship.where(user_id: current_user, micropost_id: post.id, islike: true).first
      if(is_liked)
        is_liked.destroy
      else
        VoterRelationship.create(user_id: current_user.id, micropost_id: post.id, islike: true )
      end
    end
    redirect_to :back    
  end	

  # def comment

  #   post = Micropost.where(id: params[:id]).first
  #   if post.present?      
  #       Commenter.create(user_id: current_user.id, micropost_id: post.id )      
  #   end
  #   redirect_to :back    
  # end 
end

app/helpers/user_helper.rb
module UserHelper
	# Returns the Gravatar for the given user.
  def gravatar_for(current_user)
  	# if (current_signed_in?)
  			gravatar_id = Digest::MD5::hexdigest(current_user.email.downcase)
    		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    		image_tag(gravatar_url, alt: current_user.email, class: "gravatar")
  	# end    
  end
end

app/views/users/_like.haml
= form_for(current_user.active_relationships.build, remote: true) do |f|
  %div= hidden_field_tag :user_id, @user.id
  = f.submit "like", class: "btn btn-primary"

app/views/users/index.haml
- provide(:title, 'All users')
%h1 All users
%ul.users
  - @users.each do |user|
    - if(user.id != current_user.id)
      %li
        = gravatar_for user
        = link_to user.email, users_show_path(user.id)
= will_paginate

app/views/users/request.haml
- provide(:title, 'All users')
%h1 Pending Request
%ul.users
  - @requests.each do |request|
    %li
      = link_to request.from_id, '#'
= will_paginate

app/views/users/show.haml
- provide(:title, @user.email)
.row
  %aside.col-md-4
    %section.user_info
      %h1
        = gravatar_for @user
        = @user.email
      %h2
        - if current_user.is_friend?(@user.id) || @user.is_friend?(current_user.id)
          = link_to "Remove Friend",  reject_request_path(@user.id), class: "btn btn-primary", method: :delete
        - elsif current_user.is_pending_request?(@user.id)
          = link_to "Request Sent", add_friend_path(@user.id), class: "btn btn-primary", disabled: "disabled"
        - else
          = link_to "Add Friend", add_friend_path(@user.id), class: "btn btn-primary"
  .col-md-8
    - if @user.microposts.any?
      %h3
        Microposts (#{@user.microposts.count})
      %ol.microposts
        = render @microposts
      = will_paginate @microposts