config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users
  get 'users/:id' => 'users#show', as: 'users_show'
  get 'users'=> 'users#index'

  resources :microposts,          only: [:index, :edit, :create, :destroy]
  
  get 'addfriend/:id' => 'friendship#friend_request', as: 'add_friend'

  get 'requests' => 'friendship#pending_request', as: 'pending_request'

  get 'friends' => 'friendship#friends', as: 'friends'
 
  get 'accecpt_request/:id' => 'friendship#friend_request_accept' , as: 'accecpt_request'

  delete 'reject_request/:id' => 'friendship#friend_request_reject' , as: 'reject_request'

  get 'like/:id' => 'users#like' , as: 'like_unlike' 

  get 'posts/:id' =>'microposts#showpost', as: 'posts_show'

  post 'add_comment' =>  'microposts#add_comment', as: 'add_comment'

  

 

    

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user, :foreign_key => "from_id"
	# belongs_to :to_user, :foreign_key => "to_id"
end

app/controllers/friendship_controller.rb
class FriendshipController < ApplicationController

	def friend_request
	  unless (current_user.is_pending_request?(params[:id]))	
		  from_id = current_user.id
		  to_id = params[:id] 
		  friendship = Friendship.create(from_id: from_id, to_id: to_id, accepted: false)
		  redirect_to users_show_path(to_id)
		else
			redirect_to root_path
		end  
	end
	
	def friend_request_accept
	  @friendship = Friendship.where(to_id: current_user.id, from_id: params[:id]).first
	  @friendship.update_attributes(accepted: true)
	  redirect_to :back
	end

	def friend_request_reject
	  friendship = Friendship.where(to_id: params[:id], from_id: current_user.id).first
	  friendship1 = Friendship.where(to_id: current_user.id, from_id: params[:id]).first
	  unless friendship.nil?
	  	friendship.destroy
		end
	  unless friendship1.nil?
	  	friendship1.destroy
	  end
	  redirect_to :back
	end

	def pending_request
		@requests = Friendship.where(to_id: current_user.id, accepted: false)
		#Redirect_to pending_request_path 
	end

	def friends
	 	# scope :friendship_id, :conditions=>['to_id = current_user.id OR from_id = current_user.id']
  	# scope :friendship_accept, :conditions=>['accepted = true']
  	# @friends = Friendship.friendship_id.friendship_accept

	 	 friends = Friendship.where(to_id: current_user.id, accepted: true)
	 	 friends1 = Friendship.where(from_id: current_user.id, accepted: true)

	 	 
	 # 	@friends = Event :Friendship, :conditions=>['to_id == current_user.id OR from_id == current_user.id']
		# @friends1 = Friendship.where(accepted: true)
		@fr = friends + friends1 	
		#edirect_to pending_request_path 
		#@friends = current_user.get_friends
	end

end

app/helpers/friendship_helper.rb
module FriendshipHelper
end

app/views/friendship/friends.html.erb
<% provide(:title, 'All users') %>
	<h1>Friend List</h1>
	<ul class="users">
	   <% @fr.each do |friend| %>
	    <li>
	    	<%= gravatar_for friend.user %>	
	      <%= link_to friend.user.email, users_show_path(friend.user.id) %>
	    </li>
	   <% end %>
	</ul>

app/views/friendship/pending_request.html.erb
<% provide(:title, 'All users') %>
<h1>Pending Request</h1>

<%#= will_paginate %>

<ul class="users">
   <% @requests.each do |request| %>
    <li>
    	<%# if(requests.nil?) %>
   		<!-- <li>	<h2> There is no Pending Request </h2> </li>	 -->
   		<%# else %>
	    	<%= gravatar_for request.user %>	
	      <%= link_to request.user.email, '#' %>
	      <%= link_to "Accept", accecpt_request_path(request.user.id) , class: "btn btn-primary"  %>
	      <%= link_to "Reject", reject_request_path(request.user.id) , class: "btn btn-primary"  %>
	      <%# end %>
    </li>
   <% end %>
   
</ul>

<%#= will_paginate %>