config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users
  get 'users/:id' => 'users#show', as: 'users_show'
  get 'users'=> 'users#index'

  resources :microposts,          only: [:index, :edit, :create, :destroy]
  
  get 'addfriend/:id' => 'friendship#friend_request', as: 'add_friend'

  get 'requests' => 'friendship#pending_request', as: 'pending_request'

  get 'friends' => 'friendship#friends', as: 'friends'
 
  get 'accecpt_request/:id' => 'friendship#friend_request_accept' , as: 'accecpt_request'

  delete 'reject_request/:id' => 'friendship#friend_request_reject' , as: 'reject_request'

  get 'like/:id' => 'users#like' , as: 'like_unlike' 

  get 'posts/:id' =>'microposts#showpost', as: 'posts_show'

  post 'add_comment' =>  'microposts#add_comment', as: 'add_comment'

  

 

    

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true 
  validates :content, presence: true, length: { maximum: 250 },:unless => :picture?
  # validates :comments, presence: true, length: { maximum: 100}
  validate  :picture_size
  has_many :voter_relationships
  has_many :commenters

  def is_like?(current_user)
    like = VoterRelationship.where(micropost_id: self.id, user_id: current_user.id).first
    if like.nil?
      true
    else
      false
    end
  end

  def number_of_likes
    nl = VoterRelationship.where(micropost_id: self.id, islike: true)
    nl.count
  end

  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	before_action :correct_user,   only: :destroy

	def index
		@microposts = Micropost.all
	end

	def create
    @micropost = current_user.microposts.new(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
    	@feed_items = []
      render 'welcome/index'
    end
	end

	def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end

  def update
     @micropost = Micropost.find(params[:id])
    if @micropost.update_attributes(micropost_params)
      redirect_to @micropost
    end
  end  

  def showpost
    @posts = Micropost.find(params[:id])
    @comment = Commenter.new
    @comments = Commenter.where(micropost_id: @posts.id)
  end

  def add_comment
    @posts = Micropost.find(params[:commenter][:micropost_id])
    @comments = Commenter.where(micropost_id: @posts.id)
     @comment = Commenter.new
     @comment.user_id = params[:commenter][:user_id]
     @comment.micropost_id = params[:commenter][:micropost_id]
     @comment.comments = params[:commenter][:comments]
     if @comment.save
      flash[:success] = "Comment Successfully Added"     
      redirect_to posts_show_path(@posts.id)
     else
      render :showpost  
    end

  end

  # def show_comment
  #   @show_comment = Commenter.where(micropost_id: params[:id]) 
  # end



  private

    # def comment_params
    #   params.require(:commenter).permit(:comments, :user_id, :micropost_id)
    # end

    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.haml
%li{:id => "micropost-#{micropost.id}"}
  = link_to gravatar_for(micropost.user), '#'
  %span.user= link_to micropost.user.email, posts_show_path(micropost.id)
  %span.content
    = micropost.content
    = image_tag micropost.picture.url if micropost.picture?
  %span.timestamp
    Posted #{time_ago_in_words(micropost.created_at)} ago.

app/views/microposts/_show_comment.haml
- comments.each do |comment|
  %li
    %span.user= link_to comment.user.email, posts_show_path(comment.micropost.id)
    %br/
    %span.content
      = comment.comments
  %br/
  %br/
  %span.timestamp
    Posted #{time_ago_in_words(comment.created_at)} ago.
  %hr

app/views/microposts/showpost.haml
- micropost = @posts
= link_to gravatar_for(micropost.user), '#'
%span.user
  = link_to micropost.user.email, posts_show_path(micropost.id)
%br/
%span.content
  = micropost.content
  = word_wrap(micropost.content, :line_width => 12)
  = image_tag micropost.picture.url if micropost.picture?
%br/
%span.timestamp
  Posted #{time_ago_in_words(micropost.created_at)} ago.
  %br/
  - if current_user != micropost.user
    - if current_user.is_friend?(micropost.user.id) || current_user.is_other_user_friend?(micropost.user.id)
      - if can? :like, @micropost
        - if micropost.is_like?(current_user)
          = link_to "like",  like_unlike_path(micropost.id)
          = micropost.number_of_likes
        - else
          = link_to "unlike",  like_unlike_path(micropost.id)
          = micropost.number_of_likes
      - if can? :comment, @micropost
        = link_to "Comment", '#', id: 'comment_btn'
  - else
    = link_to "Comment", '#', id: 'comment_btn'
    = link_to "delete", micropost, method: :delete, data: { confirm: "You sure?" }
  %hr
    .comments.hide
      = form_for @comment, url: add_comment_path, method: :post do |f|
        = f.text_area :comments, placeholder: "Comment"
        = f.hidden_field :user_id, value: current_user.id
        = f.hidden_field :micropost_id , value: micropost.id
        = f.submit "Submit", class: 'btn btn-primary'
    = render "microposts/show_comment", comments: @comments