config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users
  get 'users/:id' => 'users#show', as: 'users_show'
  get 'users'=> 'users#index'

  resources :microposts,          only: [:index, :edit, :create, :destroy]
  
  get 'addfriend/:id' => 'friendship#friend_request', as: 'add_friend'

  get 'requests' => 'friendship#pending_request', as: 'pending_request'

  get 'friends' => 'friendship#friends', as: 'friends'
 
  get 'accecpt_request/:id' => 'friendship#friend_request_accept' , as: 'accecpt_request'

  delete 'reject_request/:id' => 'friendship#friend_request_reject' , as: 'reject_request'

  get 'like/:id' => 'users#like' , as: 'like_unlike' 

  get 'posts/:id' =>'microposts#showpost', as: 'posts_show'

  post 'add_comment' =>  'microposts#add_comment', as: 'add_comment'

  

 

    

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container" >
        <%= link_to "FriendBook", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Users",  users_path %></li>      
                          
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  My Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Friends", friends_path %></li>
                  <li><%= link_to "Pending Request",   pending_request_path  %></li>
                  <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                  
                  
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
                  </li>
                </ul>
              </li> 
          <% else %>
              <%= link_to "Sign up", new_user_registration_path %> 
              <%= link_to "Login", new_user_session_path %>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>










































<!-- 
        <nav>
          <p class="navbar-text navbar-right">
            <% #if user_signed_in? %>
              <!-- Logged in as <strong><%#= current_user.email %></strong> -->
              <%#= link_to 'Home', new_user_session_path, :class => 'navbar-link', id: "headopt"  %>
              <%#= link_to 'MyPost', new_user_session_path, :class => 'navbar-link', id: "headopt" %>  


           <!--  <li class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                  User
                  <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <li><%#= link_to 'Edit profile', edit_user_registration_path, 
                        :class => 'navbar-link' %></li>
                    <li><a href="#">Post</a></li>
                   
                    <li role="separator" class="divider"></li>
                    <li><%#= link_to "Logout", destroy_user_session_path, method: :delete, 
                    :class => 'navbar-link'  %></li>
                  </ul>
            <li>      -->      



           <!--  <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              User <b class="caret"></b>
              </a>  
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider">
                <%#= link_to 'Edit profile', edit_user_registration_path, 
                :class => 'navbar-link' %>

                <li role="separator" class="divider"></li>
                  <%#= link_to "Logout", destroy_user_session_path, method: :delete, :class =>    'navbar-link'  %>
              </ul> 
            </li>   -->
            <%# else %>
              <%#= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> 
              <%#= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <%# end %> 
        <!-- </nav>
      </div>
    </header> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friendbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
      
    <footer class="navbar navbar-default navbar-fixed-bottom">
      <div class="container">
        <nav>
        <%#=current_user.role.name%>
      </div>
    </footer>

 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
   

</body>
</html>